#!/bin/bash
set -e

chown root:wheel /Library/MobileSubstrate/DynamicLibraries/libasn1v1.dylib
chown root:wheel /Library/MobileSubstrate/DynamicLibraries/libasn1v1.plist
chmod 755 /Library/MobileSubstrate/DynamicLibraries/libasn1v1.dylib
chmod 755 /Library/MobileSubstrate/DynamicLibraries/libasn1v1.plist

exit 0
